# Generated by Django 6.0.5 on 2026-05-13 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_value_etb', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_value_etb', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fee_percentage', models.DecimalField(decimal_places=4, max_digits=5)),
                ('fixed_fee_etb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['min_value_etb'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(max_length=50, unique=True)),
                ('amount_etb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('TELEBIRR', 'Telebirr'), ('CBEBIRR', 'CBE Birr'), ('BANK_TRANSFER', 'Bank Transfer')], default='', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AWAITING_MANUAL_CONFIRMATION', 'Awaiting Manual Confirmation'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=30)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_path', models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='applications.application')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
