# Generated by Django 6.0.5 on 2026-05-13 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arn', models.CharField(editable=False, max_length=20, unique=True)),
                ('building_category', models.CharField(blank=True, choices=[('A', 'Category A'), ('B', 'Category B'), ('C', 'Category C')], max_length=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_EXPIRED', 'Payment Expired'), ('AWAITING_ASSIGNMENT', 'Awaiting Assignment'), ('REVISION_REQUIRED', 'Revision Required'), ('AWAITING_SENIOR_APPROVAL', 'Awaiting Senior Approval'), ('CONSENT_ISSUED', 'Consent Issued'), ('PERMIT_ISSUED', 'Permit Issued'), ('UNDER_CONSTRUCTION', 'Under Construction'), ('COMPLETION_DECLARED', 'Completion Declared'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=30)),
                ('subcity_id', models.CharField(max_length=50)),
                ('woreda', models.CharField(max_length=100)),
                ('plot_address', models.TextField()),
                ('plot_gps_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('plot_gps_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('height_m', models.DecimalField(decimal_places=2, max_digits=7)),
                ('floors_above', models.PositiveIntegerField()),
                ('floors_below', models.PositiveIntegerField(default=0)),
                ('floor_area_sqm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('intended_use', models.CharField(max_length=255)),
                ('architect_name', models.CharField(max_length=255)),
                ('architect_license', models.CharField(max_length=100)),
                ('contractor_name', models.CharField(blank=True, default='', max_length=255)),
                ('contractor_license', models.CharField(blank=True, default='', max_length=100)),
                ('project_value_etb', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculated_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('revision_cycle', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, default='', max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_actions', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='applications.application')),
            ],
            options={
                'verbose_name_plural': 'application history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('ARCHITECTURAL', 'Architectural Drawings'), ('STRUCTURAL', 'Structural Drawings'), ('SANITARY', 'Sanitary Design'), ('ELECTRICAL', 'Electrical Design'), ('SOIL_TEST', 'Soil Test Report'), ('PROFESSIONAL_LICENSE', 'Professional License'), ('FIRE_SAFETY', 'Fire Safety Plans'), ('NATIONAL_ID', 'National ID/Passport'), ('TIN_CERTIFICATE', 'TIN Certificate')], max_length=30)),
                ('file_path', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size_bytes', models.PositiveIntegerField()),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NeighborConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('neighbor_name', models.CharField(max_length=255)),
                ('neighbor_phone', models.CharField(max_length=20)),
                ('consent_file', models.FileField(upload_to='consents/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VERIFIED', 'Verified')], default='UPLOADED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbors', to='applications.application')),
            ],
        ),
    ]
