# Generated by Django 6.0.5 on 2026-05-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_document_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('ARCHITECTURAL', 'Architectural Drawings'), ('STRUCTURAL', 'Structural Drawings'), ('SANITARY', 'Sanitary Design'), ('ELECTRICAL', 'Electrical Design'), ('SOIL_TEST', 'Soil Test Report'), ('PROFESSIONAL_LICENSE', 'Professional License'), ('FIRE_SAFETY', 'Fire Safety Plans'), ('NATIONAL_ID', 'National ID/Passport'), ('TIN_CERTIFICATE', 'TIN Certificate'), ('RECEIPT', 'Payment Receipt')], max_length=30),
        ),
    ]
