# Generated by Django 6.0.5 on 2026-05-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('ARCHITECTURAL', 'Architectural Drawings'), ('STRUCTURAL', 'Structural Drawings'), ('SANITARY', 'Sanitary Design'), ('ELECTRICAL', 'Electrical Design'), ('SOIL_TEST', 'Soil Test Report'), ('PROFESSIONAL_LICENSE', 'Professional License'), ('FIRE_SAFETY', 'Fire Safety Plans'), ('NATIONAL_ID', 'National ID/Passport'), ('TIN_CERTIFICATE', 'TIN Certificate'), ('RECEIPT', 'Payment Receipt'), ('CONSENT', 'Planning Consent'), ('PERMIT', 'Construction Permit'), ('COMPLETION_PHOTO', 'Completion Photo')], max_length=30),
        ),
    ]
