# Generated by Django 6.0.5 on 2026-05-13 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permit_number', models.CharField(max_length=30, unique=True)),
                ('permit_type', models.CharField(choices=[('PLANNING_CONSENT', 'Planning Consent'), ('CONSTRUCTION', 'Construction Permit'), ('COMPLETION', 'Completion Certificate')], max_length=20)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=10)),
                ('document_path', models.FileField(blank=True, upload_to='permits/%Y/%m/%d/')),
                ('qr_code_token', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='applications.application')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_permits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
